version: "3.0"

services:
  mongo:
    image: mongo
    container_name: mongo_db_after_3
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/configdb
      - mongo:/data/db

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongo: {}
